spring:
  application:
    name: csjl
  datasource:
    hikari:
      maximum-pool-size: 1000
      auto-commit: 'true'
      pool-name: DatebookHikariCP
      idle-timeout: 30000
      minimum-idle: 5
      connection-timeout: 30000
    url: >-
      jdbc:mysql://10.6.5.11:63306/zt_stock_center?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    password: Z2EjrAhw1gUW46exz5
    username: nieyongjia
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8999

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/**/*.xml
  type-aliases-package: com.longyi.csjl.domain.dto
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql