spring:
  application:
    name: mclongyi
  redis:
    enabled: true
    password:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        shutdown-timeout: 100
        max-idle: 8
        max-wait: 30
        min-idle: 8
server:
  port: 9090
